apiVersion: v1
kind: ConfigMap
metadata:
  name: wordpress-config
  namespace: prod-env
data:
  WORDPRESS_DB_HOST: "tonywpserver.mysql.database.azure.com"
  WORDPRESS_DB_NAME: "wpdatabaseprod"
  WORDPRESS_DB_USER: "tonyadmin"
  WORDPRESS_DB_PASSWORD: "Itssecret1."
